name = "SIIP2PRAS"
uuid = "4b496c86-8d00-441d-b504-079c710e0aa7"
authors = ["Surya Chandan Dhulipala <suryachandan.dhulipala@nrel.gov>"]
version = "0.4.1"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
PRAS = "05348d26-1c52-11e9-35e3-9d51842d34b9"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
